"""
memory/jira_client.py — VerdictAI Jira Integration
Creates a Jira issue on consecutive test failures.
"""

import os
import json
import base64
import urllib.request
import urllib.error


def create_jira_issue(test_id: str, suite_name: str, reason: str, fail_count: int):
    """
    Create a Jira issue for a self-heal trigger.

    Reads from env:
        JIRA_URL, JIRA_EMAIL, JIRA_API_TOKEN,
        JIRA_PROJECT_KEY, JIRA_ISSUE_TYPE
    """
    url        = os.getenv("JIRA_URL")
    email      = os.getenv("JIRA_EMAIL")
    token      = os.getenv("JIRA_API_TOKEN")
    project    = os.getenv("JIRA_PROJECT_KEY", "VQA")
    issue_type = os.getenv("JIRA_ISSUE_TYPE", "Task")

    if not all([url, email, token]):
        print("   ⚠️  JIRA_URL / JIRA_EMAIL / JIRA_API_TOKEN not set — skipping Jira issue.")
        return

    credentials = base64.b64encode(f"{email}:{token}".encode()).decode()

    payload = json.dumps({
        "fields": {
            "project":   {"key": project},
            "issuetype": {"name": issue_type},
            "summary":   f"[VerdictAI] Self-Heal: {test_id} failed {fail_count}x consecutively",
            "description": {
                "type":    "doc",
                "version": 1,
                "content": [
                    {
                        "type": "paragraph",
                        "content": [
                            {
                                "type": "text",
                                "text": (
                                    f"Test ID: {test_id}\n"
                                    f"Suite: {suite_name}\n"
                                    f"Consecutive Failures: {fail_count}\n\n"
                                    f"Latest Judge Reason:\n{reason}\n\n"
                                    f"Action Required: Review test case definition or expected behavior.\n\n"
                                    f"Auto-generated by VerdictAI self-healing trigger."
                                )
                            }
                        ]
                    }
                ]
            }
        }
    }).encode("utf-8")

    req = urllib.request.Request(
        f"{url}/rest/api/3/issue",
        data=payload,
        headers={
            "Authorization": f"Basic {credentials}",
            "Content-Type":  "application/json",
            "Accept":        "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req) as resp:
            issue = json.loads(resp.read())
            issue_key = issue.get("key", "unknown")
            print(f"   🎫 Jira issue created: {url}/browse/{issue_key}")
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"   ❌ Jira issue failed: {e.code} {e.reason} — {body}")