"""
memory/self_heal.py — VerdictAI Self-Healing Trigger
Fires on N consecutive failures for a test_id.
Actions: log warning + flag in SQLite + create GitHub issue.
"""

import os
import json
import urllib.request
import urllib.error
from memory.store import get_consecutive_failures, _get_conn
from memory.jira_client import create_jira_issue


def check_and_heal(test_id: str, suite_name: str, reason: str, n: int = 3):
    """
    Check consecutive failures and trigger self-healing actions.

    Args:
        test_id:    Test case ID.
        suite_name: Suite name for context.
        reason:     Latest judge reason (for GitHub issue body).
        n:          Consecutive failure threshold (default 3).
    """
    count = get_consecutive_failures(test_id, n=n)

    if count < n:
        return

    print(f"\n🚨 SELF-HEAL TRIGGERED: {test_id} failed {count} times in a row.")

    _flag_in_db(test_id, suite_name, count)
    _create_github_issue(test_id, suite_name, reason, count)        
    create_jira_issue(test_id, suite_name, reason, count)


def _flag_in_db(test_id: str, suite_name: str, fail_count: int):
    """Flag test as needing review in a dedicated table."""
    with _get_conn() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS flagged_tests (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                test_id     TEXT NOT NULL,
                suite_name  TEXT NOT NULL,
                fail_count  INTEGER,
                flagged_at  TEXT NOT NULL,
                resolved    INTEGER DEFAULT 0
            )
        """)
        from datetime import datetime
        conn.execute("""
            INSERT INTO flagged_tests (test_id, suite_name, fail_count, flagged_at)
            VALUES (?, ?, ?, ?)
        """, (test_id, suite_name, fail_count, datetime.utcnow().isoformat()))
        conn.commit()
    print(f"   📋 Flagged in SQLite for review.")


def _create_github_issue(test_id: str, suite_name: str, reason: str, fail_count: int):
    """
    Create a GitHub issue via API.
    Requires GITHUB_TOKEN and GITHUB_REPO in config.env.
    """
    token = os.getenv("GITHUB_TOKEN")
    repo  = os.getenv("GITHUB_REPO")  # format: owner/repo-name

    if not token or not repo:
        print("   ⚠️  GITHUB_TOKEN or GITHUB_REPO not set — skipping GitHub issue.")
        return

    title = f"[VerdictAI] Self-Heal: {test_id} failed {fail_count}x consecutively"
    body  = (
        f"## 🚨 Consecutive Failure Alert\n\n"
        f"**Test ID:** `{test_id}`\n"
        f"**Suite:** `{suite_name}`\n"
        f"**Consecutive Failures:** {fail_count}\n\n"
        f"**Latest Judge Reason:**\n> {reason}\n\n"
        f"**Action Required:** Review test case definition, "
        f"expected behavior, or model prompt.\n\n"
        f"*Auto-generated by VerdictAI self-healing trigger.*"
    )

    payload = json.dumps({
        "title": title,
        "body": body,
        "labels": ["verdictai", "self-heal", "bug"],
    }).encode("utf-8")

    url = f"https://api.github.com/repos/{repo}/issues"
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req) as resp:
            issue = json.loads(resp.read())
            print(f"   🐛 GitHub issue created: {issue.get('html_url')}")
    except urllib.error.HTTPError as e:
        print(f"   ❌ GitHub issue failed: {e.code} {e.reason}")
